#!/usr/bin/env bash

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create an HTML file with the string "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restart Nginx without using systemctl
sudo service nginx  restart
