#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get update
sudo apt-get install -y nginx
# Create an HTML file with the string "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Nyakuji permanent;/" /etc/nginx/sites-available/default
# Restart Nginx without using systemctl
sudo service nginx restart
