#!/usr/bin/env bash

# Script that installs Nginx server and redirects /redirect_me
sudo apt-get update -y
sudo apt-get install -y nginx

# Set Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Reload Nginx configuration
sudo /etc/init.d/nginx reload

# Create an HTML file with the string "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Nyakuji permanent;/" /etc/nginx/sites-available/default
# Restart Nginx without using systemctl
sudo /etc/init.d/nginx restart
