#!/usr/bin/env bash
# Script that installs Nginx and custom 404 page
sudo apt-get update -y
sudo apt-get install -y nginx

# Set Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-enabled/default

# Reload Nginx configuration
sudo /etc/init.d/nginx reload

# Create an HTML file with the string "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Nyakuji permanent;/" /etc/nginx/sites-enabled/default

#creating 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Insert the custom error_page configuration after "listen 80 default_server"
sudo sed -i "s/listen 80;/listen 80;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-enabled/default

# Restart Nginx without using systemctl
sudo /etc/init.d/nginx restart
