#!/usr/bin/env bash
#Configuring Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get install -y nginx

# Create an HTML file with the string "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Nyakuji permanent;/" /etc/nginx/sites-enabled/default

#creating 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Insert the custom error_page configuration after "listen 80 default_server"
sudo sed -i "s/listen 80;/listen 80;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-enabled/default

#Custom HTTP response header
sudo sed -i '/server_name _/a\    add_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default

#Test for syntax error
sudo nginx -t
# Restart Nginx without using systemctl
sudo service nginx restart
