#!/usr/bin/env bash
# shellcheck disable=SC2016
# installing and config load balancer

# Install required packages
sudo apt-get -y install software-properties-common

# Add HAProxy PPA
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0

# Update package list
sudo apt-get -y update

# Install HAProxy version 2.0
sudo apt-get -y install haproxy=2.0.*

# Enable HAProxy service
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Append HAProxy configuration to haproxy.cfg
echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 112615-web-01 52.86.205.42:80 check
    server 112615-web-02 54.82.176.167:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
# sudo service haproxy restart
