#!/usr/bin/env bash
#This script displays "Best School" 10 times. On the 9th iteration, it displays
"Best School" and  "Hi" on a new line.

#Initialize the count
count=1

#The while loop to display "Best School" 10 times
while [ $count -lt 10 ]; do
    echo "Best School"
    if [ $count -eq 9 ]
    then
    echo "Hi"
    fi
    ((count++))
done
