#!/usr/bin/env bash
#This script displays "Best School" 10 times. On the 9th iteration, it displays
"Best School" and  "Hi" on a new line.

#Initialize the count
count=0

#The while loop to display "Best School" 10 times
while [ $count -lt 10 ]; do
    #Check if it's the 9th iteration
    if [ $count -eq 8 ]
    then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi

    #Increment rhe count
    ((count++))
done
