#!/usr/bin/env bash
# Update the Nginx user in the configuration
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Update the Nginx worker processes to 4 (you can adjust this number based on your needs)
sed -i 's/worker_processes auto;/worker_processes 4;/g' /etc/nginx/nginx.conf

# Ensure Nginx is listening on all active IPs on port 8080
sed -i 's/listen 80 default_server;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

# Check the Nginx processes and verify if it's listening on port 8080
ps auxff | grep ngin[x]
nc -z 0 8080
